SESSION=hyprland
CATEGORIES=desktop-common,apps,dev,gaming,virtualization,flatpak-gaming
PACKAGES=calf,ckb-next,easyeffects,keyd,lsp-plugins-lv2,nvtop,wiremix
ARCH_PACKAGES=amd-ucode,libva-nvidia-driver,nvidia-open,nvidia-settings,nvidia-utils
