SESSION=hyprland
CATEGORIES=desktop-common,apps,dev,gaming,virtualization,flatpak-gaming
PACKAGES=amd-ucode,calf,ckb-next,easyeffects,keyd,libva-nvidia-driver,lsp-plugins-lv2,nvtop,nvidia-open,nvidia-settings,nvidia-utils,wiremix
