SESSION=hyprland
CATEGORIES=desktop-common,apps,dev,gaming,virtualization,gaming/flatpak,hardware/nvidia-gpu,hardware/power-profiles
PACKAGES=calf,ckb-next,easyeffects,lsp-plugins-lv2,nvtop,wiremix
ARCH_PACKAGES=amd-ucode
