general {
  resize_on_border = false
  allow_tearing = true
  layout = scrolling
}

dwindle {
  pseudotile = true
  preserve_split = true
  force_split = 2
}

misc {
  middle_click_paste = false
  force_default_wallpaper = -1
  disable_hyprland_logo = false
}
