exec-once = hyprpm reload -n
#exec-once = ~/.local/bin/audiosetup.sh

source = ~/.local/share/nova/defaults/hypr/startup.conf
source = ~/.local/share/nova/defaults/hypr/binds.conf
source = ~/.local/share/nova/defaults/hypr/looknfeel.conf
source = ~/.local/share/nova/defaults/hypr/rules.conf

#source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/binds.conf
#source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/rules.conf

source = ~/.config/hypr/dms/binds.conf
source = ~/.config/hypr/dms/colors.conf
source = ~/.config/hypr/dms/cursor.conf
source = ~/.config/hypr/dms/layout.conf
source = ~/.config/hypr/dms/outputs.conf
source = ~/.config/hypr/dms/windowrules.conf
