source = ~/.config/hypr/general.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/overlays/current.conf

plugin {
  hyprsplit {
    num_workspaces = 10
  }

  dynamic-cursors {
    mode = none
    shake {
      treshold = 5.0
    }
  }

  hyprscrolling {
    fullscreen_on_one_column = true
  }
}

workspace = special:audiomixer, on-created-empty:uwsm app -- xdg-terminal-exec --app-id=com.nova-desktop.special.audiomixer -- pulsemixer
workspace = special:processes, on-created-empty:uwsm app -- xdg-terminal-exec --app-id=com.nova-desktop.special.processes -- btop
workspace = special:pwmanager, on-created-empty:uwsm app -- bitwarden-desktop
workspace = special:scratchpad, on-created-empty:uwsm app -- xdg-terminal-exec --app-id=com.nova-desktop.special.scratchpad
workspace = special:calculator, on-created-empty:uwsm app -- xdg-terminal-exec --app-id=com.nova-desktop.special.calculator -- qalc
workspace = special:musicplayer, on-created-empty:uwsm app -- spotify-launcher

layerrule = blur on, match:namespace gtk4-layer-shell
layerrule = ignore_alpha 0, match:namespace gtk4-layer-shell
