input {
  kb_layout = us,fi
  kb_variant =
  kb_model =
  kb_options = compose:menu
  kb_rules =

  follow_mouse = 1

  sensitivity = 0

  touchpad {
    natural_scroll = true
  }
}

gesture = 3, horizontal, workspace

bind = SUPER, Q, killactive,
bind = SUPER, return, exec, uwsm app -- xdg-terminal-exec
bind = SUPER, space, exec, dms ipc call spotlight toggle
bind = SUPER SHIFT, Q, exec, dms ipc call powermenu toggle
bind = SUPER, E, exec, uwsm app -- $(xdg-mime query default inode/directory)
bind = SUPER, F, togglefloating
bind = SUPER, W, exec, uwsm app -- $(xdg-mime query default x-scheme-handler/https)
bind = SUPER, period, exec, uwsm app emote
bind = SUPER, X, exec, loginctl lock-session
bind = SUPER, S, split:swapactiveworkspaces, current +1
bind = SUPER, less, exec, screenshot-upload
bind = SUPER SHIFT, less, exec, screenshot-clipboard
bind = SUPER, V, exec, dms ipc call clipboard toggle
bind = SUPER, G, exec, dms ipc call processlist focusOrToggle
bind = SUPER, M, fullscreen
bind = SUPER, I, exec, hyprctl switchxkblayout all next

bind = SUPER, R, togglespecialworkspace, processes
bind = SUPER, minus, togglespecialworkspace, scratchpad
bind = SUPER, A, togglespecialworkspace, musicplayer
bind = SUPER SHIFT, A, togglespecialworkspace, audiomixer
bind = SUPER, D, togglespecialworkspace, pwmanager
bind = SUPER, C, togglespecialworkspace, calculator

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, L, movewindow, r

bind = SUPER, 1, split:workspace, 1
bind = SUPER, 2, split:workspace, 2
bind = SUPER, 3, split:workspace, 3
bind = SUPER, 4, split:workspace, 4
bind = SUPER, 5, split:workspace, 5
bind = SUPER, 6, split:workspace, 6
bind = SUPER, 7, split:workspace, 7
bind = SUPER, 8, split:workspace, 8
bind = SUPER, 9, split:workspace, 9
bind = SUPER, 0, split:workspace, 10

bind = SUPER SHIFT, 1, split:movetoworkspacesilent, 1
bind = SUPER SHIFT, 2, split:movetoworkspacesilent, 2
bind = SUPER SHIFT, 3, split:movetoworkspacesilent, 3
bind = SUPER SHIFT, 4, split:movetoworkspacesilent, 4
bind = SUPER SHIFT, 5, split:movetoworkspacesilent, 5
bind = SUPER SHIFT, 6, split:movetoworkspacesilent, 6
bind = SUPER SHIFT, 7, split:movetoworkspacesilent, 7
bind = SUPER SHIFT, 8, split:movetoworkspacesilent, 8
bind = SUPER SHIFT, 9, split:movetoworkspacesilent, 9
bind = SUPER SHIFT, 0, split:movetoworkspacesilent, 10

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 set 5%-

bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
