SESSION=niri
CATEGORIES=desktop-common,apps,dev
PACKAGES=keyd
ARCH_PACKAGES=brightnessctl,bluez,bluez-utils,intel-media-driver,intel-ucode,lib32-nvidia-utils,lib32-vulkan-intel,libvdpau,nvidia-open,nvidia-prime,nvidia-utils,nvtop,sof-firmware,tlp,tlp-pd,vulkan-intel
